config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards, :banks, :conditions, :airlines
  resources :promotions, except: [:index, :show]
  resources :coefficients, except: [:index, :show]

  namespace :api do
    namespace :v1 do
      get 'promotions_app/airlines_credit_cards_banks_data'
      get 'promotions_app/compatible_promotions'
      get 'promotions_app/compatible_coefficients'      
      get 'promotions_app/all_promotions'
      get 'promotions_app/airlines_credit_cards_banks_promotions_data'
    end
  end

  get '/logout' => 'application#logout'

  patch 'promotions/:id/enable',:to => "promotions#enable"
  patch 'promotions/:id/disable',:to => "promotions#disable"
  post 'promotions/:id/clone',:to => "promotions#clone"

  post 'airlines/:id/clone',:to => "airlines#clone"

  patch 'coefficients/:id/enable',:to => "coefficients#enable"
  patch 'coefficients/:id/disable',:to => "coefficients#disable"
  post 'coefficients/:id/clone',:to => "coefficients#clone"

  root 'conditions#index'

end

app/models/condition.rb
class Condition < ActiveRecord::Base

    belongs_to :airline
    has_many :promotions, dependent: :destroy
    has_many :coefficients, dependent: :destroy 
    
    validates_presence_of :start_date
    validates_presence_of :end_date
    validate :dates, unless: "start_date.nil? || end_date.nil?"
    
    # validate :promotions_rel
    validate :coefficients_rel
    validate :promotions_dates, unless: "promotions.blank?"
    validate :coefficients_dates, unless: "coefficients.blank?"
    
    scope :by_airline, ->(desired_id) { where(airline_id: [desired_id,nil])}

    def have_promotions
        if self.promotions.empty?
            return false        
        end
        return true
    end

    def validate_dates_of_my_promotions
        self.promotions.each do |promotion| 
            return true if !promotion.between_dates(self.start_date, self.end_date)
        end
        return false
    end

    def validate_dates_of_my_coefficients
        self.coefficients.each do |coefficient| 
            return true if !coefficient.between_dates(self.start_date, self.end_date)
        end
        return false
    end  

    private
        def dates
            errors.add(:dates, "La fecha de inicio debe ser anterior a la fecha de fin.") if self.start_date > self.end_date
        end

        def airline_val
            errors.add(:airline, "Debe seleccionar una aerolinea.") if self.airline.blank?
        end

        def promotions_rel
            errors.add(:promotions, "Debe crear al menos una promocion.") if self.promotions.blank?
        end

        def coefficients_rel
            errors.add(:coefficients, "Debe crear al menos un coeficiente.") if self.coefficients.blank?
        end

        def promotions_dates
            errors.add(:promotions, "Las fechas de las promociones deben estar dentro del rango de fechas de la condicion.") if self.validate_dates_of_my_promotions
        end

        def coefficients_dates
            errors.add(:coefficients, "Las fechas de los coeficientes deben estar dentro del rango de fechas de la condicion.") if self.validate_dates_of_my_coefficients
        end       
end

app/controllers/conditions_controller.rb
require 'csv'
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:show, :edit, :destroy]
  before_action :set_airlines, only: [:edit, :new]

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"condition-list.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end    
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
    @promotions = @condition.promotions
    @coefficients = @condition.coefficients
  end

  # GET /conditions/new
  # Si se aprieta en nueva condicion y se vuelve para atràs, se crea una condiciòn vacìa. A reparar.
  def new
    @condition = Condition.new
    @condition.save(:validate => false)
    @promotions = []
    @coefficients = []    
  end

  # POST /conditions
  # POST /conditions.json
  def create
    condition_service = ServiceCondition.new(condition_params)
    @condition = condition_service.add_complete_data_to_condition
    respond_to do |format|
      if @condition.save
        format.html { redirect_to @condition, notice: 'La condicion se ha creado con exito.' }
      else
        @airline = Airline.find(condition_params[:airline]) unless condition_params[:airline].blank?
        @airlines = Airline.all.map { |airline| [airline.name, airline.id] }
        @promotions = Promotion.all.where(condition_id: @condition.id)
        @coefficients = Coefficient.all.where(condition_id: @condition.id)
        format.html { render :new }
      end
    end
  end

  # def create
  #   @condition = Condition.new
  #   @condition.save(:validate => false)
  #   p 'manu'
  #   p condition_params["id"]
  #   p @condition.id.to_s 
  #   condition_params["id"]=@condition.id.to_s
  #   p condition_params
  #   condition_service = ServiceCondition.new(condition_params)
  #   @condition = condition_service.add_complete_data_to_condition
  #   respond_to do |format|
  #     if @condition.save
  #       format.html { redirect_to @condition, notice: 'La condicion se ha creado con exito.' }
  #     else
  #       @condition.destroy
  #       @airline = Airline.find(condition_params[:airline]) unless condition_params[:airline].blank?
  #       @airlines = Airline.all.map { |airline| [airline.name, airline.id] }
  #       @promotions = Promotion.all.where(condition_id: @condition.id)
  #       @coefficients = Coefficient.all.where(condition_id: @condition.id)
  #       format.html { render :new }
  #     end
  #   end
  # end

  
  # GET /conditions/1/edit
  def edit
    @condition.start_date = @condition.start_date.strftime("%d/%m/%Y") unless @condition.start_date.nil?
    @condition.end_date = @condition.end_date.strftime("%d/%m/%Y") unless @condition.end_date.nil?
    @promotions = @condition.promotions
    @coefficients = @condition.coefficients
    @render_hidden_input = true
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
    condition_service = ServiceCondition.new(condition_params)
    @condition = condition_service.add_complete_data_to_condition()
    respond_to do |format|
      if @condition.valid?
        @condition.save
        format.html { redirect_to @condition, notice: 'La condicion se actualizado con exito.' }
      else
        @airline = @condition.airline
        @airlines = Airline.all.map { |airline| [airline.name, airline.id] }
        @promotions = Promotion.all.where(condition_id: @condition.id)
        @coefficients = Coefficient.all.where(condition_id: @condition.id)
        format.html { render :edit }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    @condition.destroy
    respond_to do |format|
      format.html { redirect_to conditions_url, notice: 'La condicion ha sido eliminada con exito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    def set_airlines
      @airlines = Airline.all.map { |airline| [airline.name, airline.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition)
    end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/edit.html.erb
<h1>Editar condicion <%=@condition.shortname%></h1>
<br>
<script>
  $(document).ready(function() { 
    $("#condition_airline_id").select2();
    $('.date').mask("00/00/0000", {placeholder: "__/__/____"});
    Mousetrap.bind('shift+p',function (e) {
      $('#button_new_promotion').trigger("click");
    });
    Mousetrap.bind('shift+c',function (e) {
      $('#button_new_coefficient').trigger("click");
    });
  });
</script>

<%= form_for(@condition) do |f| %>

  <% if @condition.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>No se ha podido guardar por los siguientes errores:</h2>

      
      <% @condition.errors.values.each do |message| %>
        <%= message %>
      <% end %>
      
    </div>
  <% end %>
  <input type="hidden" name="condition[id]" value="<%= @condition.id%>">
  <div class="row">
    <div class="col-md-4">
      <div class="control-group">
        <%= f.label "Aerolinea", :class => 'control-label' %>
        <div class="controls">
          <%= select(:condition, :airline_id, @airlines, { include_blank: true }, :class => 'form-control') %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="control-group">
        <%= f.label "Fecha de inicio", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :start_date, :required => true, :class => 'form-control date' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="control-group">
        <%= f.label "Fecha de fin", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :end_date, :required => true, :class => 'form-control date' %>
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <div class="control-group">
        <%= f.label "Activo", :class => 'control-label' %>
        <div class="controls">
          <%= f.check_box :active, :class => 'form-control' %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div>
        <%= render partial: "promotions/list", locals: {condition: @condition, promotions: @promotions} %>        
      </div>
      <div>
        <%= render partial: "coefficients/list", locals: {condition: @condition, promotions: @coefficients} %>     
      </div>
    </div>
    <!-- <div class="row"> -->
      <div class="col-md-12"> 
        <div class="control-group">
            <%= f.label "Descripcion legal", :class => 'control-label' %>
            <div class="controls">
              <%= f.text_area :legal_description, :class => 'form-control text-area-legal-description' %>
            </div>
        </div>
      </div>
    <!-- </div> -->
    <div class="col-md-3">
      <div class="actions">
        <%= f.submit "Editar condicion",:class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <span id="modal-spin" style="position: absolute;display: block;top: 50%;left: 50%;"></span>
      </div>
    </div>
  </div>
</div>
<div style="float:right;margin-top:-33px">
    <%= link_to 'Volver', conditions_path, :class => "btn btn-default"%>
</div>
<script type="text/javascript">
</script>

app/views/conditions/index.csv.erb
<%- headers = ['mongodb_id', 'shortname', 'start_date','end_date', 'legal_description', 'active', 'airline_id', 'created_at', 'updated_at'] -%>
<%= CSV.generate_line headers %>
<%- @conditions.each do |condition| -%>
  <%= CSV.generate_line([condition.id.to_s, condition.shortname, condition.start_date, condition.end_date, condition.legal_description, condition.active, condition.airline_id, condition.created_at, condition.updated_at]).html_safe %>
<%- end -%>

app/views/conditions/index.html.erb
<div class="page-header">
  <h1>Condiciones tarjetas</h1>
  <div style="float:right;margin-top:-50px">
      <%= link_to 'Nueva condicion', new_condition_path, :class => 'btn btn-primary' %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha de inicio</th>
      <th>Fecha de fin</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @conditions.each do |condition| %>
      <% delete_message = if condition.have_promotions then 'Esta condicion tiene promociones, esta seguro que desea eliminarla? ' else 'Esta seguro de eliminar esta condicion?' end %>
      <% link_text = if condition.shortname.blank? then 'Ver' else condition.shortname end %>
      <tr>
        <td><%= link_to link_text, condition_path(condition) %></td>
        <td><%= condition.start_date.strftime("%d/%m/%Y") unless condition.start_date.nil? %></td>
        <td><%= condition.end_date.strftime("%d/%m/%Y") unless condition.start_date.nil? %></td>
        <td>
          <%= link_to 'Editar', edit_condition_path(condition),:class => 'btn btn-default btn-xs' %>
          <%= link_to 'Eliminar', condition, method: :delete, data: { confirm: delete_message }, :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/conditions/new.html.erb
<h1>Nueva condicion</h1>
<script>
  $(document).ready(function() { 
    $("#condition_airline_id").select2();
    $('.date').mask("00/00/0000", {placeholder: "__/__/____"});   
    Mousetrap.bind('shift+p',function (e) {
      $('#button_new_promotion').trigger("click");
    });
    Mousetrap.bind('shift+c',function (e) {
      $('#button_new_coefficient').trigger("click");
    });
  });
</script>

<%= form_for(@condition, url: conditions_path, html: { method: "post" }  ) do |f| %>

  <% if @condition.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>No se ha podido guardar por los siguientes errores:</h2>

      
      <% @condition.errors.values.each do |message| %>
        <%= message %>
      <% end %>
      
    </div>
  <% end %>
    <input type="hidden" name="condition[id]" value="<%= @condition.id%>">
  <div class="row">
    <div class="col-md-4">
      <div class="control-group">
        <%= f.label "Aerolinea", :class => 'control-label' %>
        <div class="controls">
          <%# f.select(:airline, @airlines,{ include_blank: true }, :class => 'form-control') %>
          <%= select(:condition, :airline_id, @airlines, { include_blank: true }, :class => 'form-control') %>

        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="control-group">
        <%= f.label "Fecha de inicio", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :start_date, :required => true, :class => 'form-control date' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="control-group">
        <%= f.label "Fecha de fin", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :end_date, :required => true, :class => 'form-control date' %>
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <div class="control-group">
        <%= f.label "Activo", :class => 'control-label' %>
        <div class="controls">
          <%= f.check_box :active, :class => 'form-control' %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div>
        <%= render partial: "promotions/list", locals: {condition: @condition, promotions: @promotions} %>        
      </div>
      <div>
        <%= render partial: "coefficients/list", locals: {condition: @condition, promotions: @coefficients} %>     
      </div>
    </div>
    <div class="col-md-12"> 
      <div class="control-group">
          <%= f.label "Descripcion legal", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_area :legal_description, :class => 'form-control text-area-legal-description' %>
          </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="actions">
        <%= f.submit "Crear condicion",:class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <span id="modal-spin" style="position: absolute;display: block;top: 50%;left: 50%;"></span>
      </div>
    </div>
  </div>
</div>
<div style="float:right;margin-top:-33px">
    <%= link_to 'Volver', conditions_path, :class => "btn btn-default"%>
</div>
<script type="text/javascript">
</script>

app/views/conditions/show.html.erb
<div class="page-header">
  <h1>Condición <%=@condition.shortname%></h1>
</div>
<p>
  <strong>Nombre:</strong>
  <%= @condition.shortname unless @condition.shortname.blank? %>
</p>
<p>
  <strong>Aerolinea:</strong>
  <%= @condition.airline.name unless @condition.airline.blank? %>
</p>

<p>
  <strong>Descripcion legal:</strong>
  <%= @condition.legal_description %>
</p>

<p>
  <strong>Fecha de creacion:</strong>
  <%= @condition.created_at.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Fecha de inicio:</strong>
  <%= @condition.start_date.strftime("%d/%m/%Y") unless @condition.start_date.blank? %>
</p>

<p>
  <strong>Fecha de fin:</strong>
  <%= @condition.end_date.strftime("%d/%m/%Y") unless @condition.end_date.blank? %>
</p>

<%= render partial: "promotions/list", locals: {promotions: @promotions} %> 
<%= render partial: "coefficients/list", locals: {coefficients: @coefficients} %>        

<%= link_to 'Volver al listado', conditions_path, :class => "btn btn-default btn-xs" %>
<%= link_to 'Editar', edit_condition_path(@condition), :class => "btn btn-default btn-xs" %> 