config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards, :banks, :conditions, :airlines
  resources :promotions, except: [:index, :show]
  resources :coefficients, except: [:index, :show]

  namespace :api do
    namespace :v1 do
      get 'promotions_app/airlines_credit_cards_banks_data'
      get 'promotions_app/compatible_promotions'
      get 'promotions_app/compatible_coefficients'      
      get 'promotions_app/all_promotions'
      get 'promotions_app/airlines_credit_cards_banks_promotions_data'
    end
  end

  get '/logout' => 'application#logout'

  patch 'promotions/:id/enable',:to => "promotions#enable"
  patch 'promotions/:id/disable',:to => "promotions#disable"
  post 'promotions/:id/clone',:to => "promotions#clone"

  post 'airlines/:id/clone',:to => "airlines#clone"

  patch 'coefficients/:id/enable',:to => "coefficients#enable"
  patch 'coefficients/:id/disable',:to => "coefficients#disable"
  post 'coefficients/:id/clone',:to => "coefficients#clone"

  root 'conditions#index'

end

app/models/airline.rb
class Airline < ActiveRecord::Base
    establish_connection :AeroManu_development
    has_many :conditions

    validates_presence_of :name, message: "Debe ingresar un nombre para la aerolínea"
    validates_presence_of :iata_code, message: "Debe ingresar un iata_code para la aerolínea"
    validates_presence_of :max_age_child, message: "Debe ingresar una edad"
    validates_presence_of :max_age_infant, message: "Debe ingresar una edad"        

    def conditions=(arrayOfConditions)
        arrayOfConditions.each do | condition |
            condition.airline = self
            condition.save
        end
    end
end

app/controllers/airlines_controller.rb
require('csv')
class AirlinesController < ApplicationController
before_action :set_airline, only: [:show, :edit, :update, :destroy, :clone]    


  # GET /airlines
  # GET /airlines.json
  def index
    @airlines = Airline.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"airline-list.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end    
  end

  # GET /airlines/1
  # GET /airlines/1.json  
  def show
  end

  # GET /airlines/1/edit
  def edit
  end

  def new
    @airline = Airline.new
  end  

  def create
    @airline = Airline.new(airline_params)

    respond_to do |format|
      if @airline.save
        format.html { redirect_to airlines_path, notice: 'La aerolinea fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @airline }
      else
        format.html { render :new }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end   

  # PATCH/PUT /airlines/1
  # PATCH/PUT /airlines/1.json
  def update
    respond_to do |format|
      if @airline.update(airline_params)
        format.html { redirect_to @airline, notice: 'La aerolinea fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @bairline }
      else
        format.html { render :edit }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airlines/1
  # DELETE /airlines/1.json
  def destroy
    @airline.destroy
    respond_to do |format|
      format.html { redirect_to airlines_url, notice: 'La aerolinea fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

# POST /airlines/1/clone
  def clone
    @airline = @airline.dup
    respond_to do |format|
      if @airline.save
        @render_hidden_input = true if request.xhr?
        format.html { redirect_to airlines_url, notice: 'La aerolinea fue clonada exitosamente.' }
      else
        format.json { render :json => { :errors => @airline.errors }, :status => 409 }
      end
    end
  end
helper_method :clone  

private
    # Use callbacks to share common setup or constraints between actions.
    def set_airline
        @airline = Airline.find(params[:id])
    end

def airline_params
   params.require(:airline).permit(:name, :max_age_infant, :max_age_child, :iata_code)
end


end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/views/airlines/_form.html.erb
<%= form_for @airline, :html => { :class => "form-horizontal airline" } do |f| %>

  <% if @airline.errors.any? %>
  <% end %>

  <div class="form-group">
    <%= f.label "Nombre", :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label "Iata code", :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :iata_code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:iata_code) %>
  </div>

  <div class="form-group">
    <%= f.label "edad màxima niño", :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :max_age_child, :class => 'form-control' %>
    </div>
    <%=f.error_span(:max_age_child) %>
  </div>    

  <div class="form-group">
    <%= f.label "edad màxima infant", :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :max_age_infant, :class => 'form-control' %>
    </div>
    <%=f.error_span(:max_age_infant) %>
  </div>    

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Crear", :class => 'btn btn-primary' %>
      <%= link_to "Cancelar",
                airlines_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/airlines/edit.html.erb
<%- model_class = Airline -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/airlines/index.csv.erb
<%- headers = ['mongodb_id', 'name', 'max_age_infant','max_age_child','general_tax_id','general_markup_id','iata_code'] -%>
<%= CSV.generate_line headers %>
<%- @airlines.each do |airline| -%>
  <%= CSV.generate_line([airline.id.to_s, airline.name, airline.max_age_infant, airline.max_age_child, airline.general_tax_id, airline.general_markup_id, airline.iata_code]).html_safe %>
<%- end -%>

app/views/airlines/index.html.erb
<%- model_class = Airline -%>
<div class="page-header">
  <h1>Aerolineas</h1>
</div>
<%= link_to "Nueva",
            new_airline_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>      
    </tr>
  </thead>
  <tbody>
    <% @airlines.each do |airline| %>
      <tr>
        <td><%= link_to airline.name, airline_path(airline) %></td>
        <td>
          <%= link_to "Editar",
                      edit_airline_path(airline), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Eliminar",
                      airline_path(airline),
                      :method => :delete,
                      :data => { :confirm => "Esta seguro de eliminar esta aerolinea?" },
                      :class => 'btn btn-xs btn-danger' %>                                
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/airlines/new.html.erb
<div class="page-header">
  <h1>Crear aerolinea</h1>
</div>
<%= render :partial => 'form' %>

app/views/airlines/show.html.erb
<%- model_class = Airline -%>
<div class="page-header">
  <h1>Aerolineas</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nombre:</strong></dt>
    <dd><%= @airline.name %></dd>
  <dt><strong>Iata code:</strong></dt>
    <dd><%= @airline.iata_code %></dd>
  <dt><strong>Max edad niños:</strong></dt>
    <dd><%= @airline.max_age_child %></dd>
  <dt><strong>Max edad infant:</strong></dt>
    <dd><%= @airline.max_age_infant %></dd>
</dl>

<%= link_to "Volver",
              airlines_path, :class => 'btn btn-default'  %>
<%= link_to "Editar",
              edit_airline_path(@airline), :class => 'btn btn-default' %>
<%= link_to "Eliminar",
              airline_path(@airline),
              :method => 'delete',
              :data => { :confirm => "Esta seguro de eliminar este banco?"},
              :class => 'btn btn-danger' %>