config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards, :banks, :conditions, :airlines
  resources :promotions, except: [:index, :show]
  resources :coefficients, except: [:index, :show]

  namespace :api do
    namespace :v1 do
      get 'promotions_app/airlines_credit_cards_banks_data'
      get 'promotions_app/compatible_promotions'
      get 'promotions_app/compatible_coefficients'      
      get 'promotions_app/all_promotions'
      get 'promotions_app/airlines_credit_cards_banks_promotions_data'
    end
  end

  get '/logout' => 'application#logout'

  patch 'promotions/:id/enable',:to => "promotions#enable"
  patch 'promotions/:id/disable',:to => "promotions#disable"
  post 'promotions/:id/clone',:to => "promotions#clone"

  post 'airlines/:id/clone',:to => "airlines#clone"

  patch 'coefficients/:id/enable',:to => "coefficients#enable"
  patch 'coefficients/:id/disable',:to => "coefficients#disable"
  post 'coefficients/:id/clone',:to => "coefficients#clone"

  root 'conditions#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="turbolinks-progress-bar">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Promotions" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body >

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Condiciones", conditions_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><a target="_blank" href="http://localhost:4002">Tarjetas</a></li>
            <li><a target="_blank" href="http://localhost:4002/banks">Bancos</a></li>
            <li><%= link_to "Aerolineas", airlines_path  %></li>
          </ul>

          <p class="navbar-text navbar-right"><a href="#" class="navbar-link"><%= @current_user.name_and_surname %></a></p>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-1">
        </div><!--/span-->
      </div><!--/row-->
      <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
          <footer></footer>
        </div>
        <div class="col-lg-1">
        </div><!--/span-->
      </div><!--/row-->
      

    </div> <!-- /container -->

  </body>
</html>